# IO
io.results_dir: data/base_results
io.analysis_dir: analysis

# Simulation
sim.n_players: 5
sim.num_shuffles: 100
sim.seed: 0

# Analysis
analysis.run_trueskill: true
analysis.trueskill_beta: 4.166666666666667
analysis.n_jobs: 1
analysis.log_level: INFO
