io:
  results_dir: results
  analysis_dir: analysis
sim:
  n_players: 5
  num_shuffles: 100
  seed: 0
analysis:
  run_trueskill: true
  trueskill_beta: 4.166666666666667
  n_jobs: 1
  log_level: INFO
